apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres 
spec:
  ports:
  - port: 5432 
    name: postgres 
  clusterIP: None  # Headless Service - критично для StatefulSet
  selector:
    app: postgres 
